# Generated by Django 3.2.7 on 2021-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211118_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
