# Generated by Django 3.2.7 on 2021-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_useraccount_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('store', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('time_in', models.CharField(max_length=256)),
                ('time_out', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
