# Generated by Django 3.2.7 on 2021-12-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='time_out',
        ),
    ]
