# Generated by Django 3.2.7 on 2021-12-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_userlogs_time_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogs',
            old_name='store',
            new_name='location',
        ),
    ]
