# Generated by Django 3.2.7 on 2021-12-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_store_userlogs_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='status',
        ),
    ]
