# Generated by Django 3.2.7 on 2021-12-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_useraccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
