# Generated by Django 3.2.7 on 2021-12-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_useraccount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
    ]
