# Generated by Django 3.2.7 on 2021-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_useraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
