# Generated by Django 3.2.7 on 2022-01-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_useraccount_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('time_in', models.CharField(max_length=256)),
            ],
        ),
    ]
