# Generated by Django 3.2.7 on 2022-02-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_activelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='rfid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
